micronaut:
  application:
    name: api
  server:
    port: 8081
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/go_rest`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:root}
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
jpa:
  default:
      packages-to-scan:
          - 'api.models'
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          show_sql: true